### ISSUE TITLE
AttributeError: module 'custom_components.alexa_media' has no attribute 'setup'

### ISSUE THREAD

**Issue by hairychris** [keatontaylor/custom_components#93]
````
Error during setup of component alexa_media
````

When I start the component since upgrading to 0.88 it throws an error. It was working fine on 0.87. I have tried adjusting the file structure and replacing the files with version 1.0.0

File structure:

````
/appdata/homeassistant/custom_components/alexa_media
├── __init__.py
├── __pycache__
│   └── __init__.cpython-37.pyc
├── const.py
└── media_player.py
````

Configuration:

````
alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: "amazon.co.uk"
````

Is anyone else seeing this? Is it something I am doing wrong or a bug?

**Comment by alandtse** [comment]
Can you provide the full logs for the component setup please?
Please also:

- Verify no older versions of the component are present in custom_components
- Ensure the .py files are the raw versions from GitHub.

**Comment by chali272** [comment]
> ```
> Error during setup of component alexa_media
> ```
> When I start the component since upgrading to 0.88 it throws an error. It was working fine on 0.87. I have tried adjusting the file structure and replacing the files with version 1.0.0
> 
> File structure:
> 
> ```
> /appdata/homeassistant/custom_components/alexa_media
> ├── __init__.py
> ├── __pycache__
> │   └── __init__.cpython-37.pyc
> ├── const.py
> └── media_player.py
> ```
> Configuration:
> 
> ```
> alexa_media:
>   accounts:
>     - email: !secret alexa_email
>       password: !secret alexa_password
>       url: "amazon.co.uk"
> ```
> Is anyone else seeing this? Is it something I am doing wrong or a bug?

hi, are you using Hass.io?    then i think that you did my mistake, (the wiki is a little confusing) 
if you are using hass.io you need to download this folder https://github.com/keatontaylor/custom_components  (click download zipp)

extract the folder after downloading the zipp,  place all files in /config/custom_components/  you need to add both the folder: alexapy and the folder alexa_media
then restart .  i got the same error since i only added the folder alexa_meda withe the 3 fil inside, adding the missing folders got it working.  added a image how my looks.

<img width="659" alt="alexa" src="https://user-images.githubusercontent.com/11187523/53309585-ff46c500-38a8-11e9-9cae-cec4efc0d0bf.png">

//Regards

**Comment by alandtse** [comment]
@chali272 That's interesting that it didn't work for you without the alexapy. Are you positive the alexapy folder is necessary?  

We've had some people looking for an easy way to replace the alexapy version in hass.io, so perhaps this is a workaround.

**Comment by hairychris** [comment]
I am not using hass.io, just running homeassistant/home-assistant docker image. When downloading the zip from github the alexapy folder is empty so I shouldn't imagine it's doing anything. As it's a git submodule you'd have to clone the main repo and then the submodule, right? I tried running:

````
rm -rf /appdata/homeassistant/custom_components/media_player
rm -rf /appdata/homeassistant/custom_components/alexa*
cd /tmp
git clone --recurse-submodules -j8 https://github.com/keatontaylor/custom_components.git
mv ./custom_components/alexa* /appdata/homeassistant/custom_components
````

This results in a file structure like:

````
├── alexa_media
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-37.pyc
│   │   └── const.cpython-37.pyc
│   ├── const.py
│   └── media_player.py
├── alexapy
│   ├── LICENSE
│   ├── README.md
│   ├── alexapy
│   │   ├── __init__.py
│   │   ├── alexaapi.py
│   │   └── alexalogin.py
│   └── setup.py
````

Which is now working, the first two rm commands did not remove any files for me so it msut be alexapy related.

**Comment by alandtse** [comment]
@hairychris You're not the [first one](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1973) using docker to not get the alexapy initially. Would you be willing to test what happens if you delete the alexapy directory? I don't think the local alexapy is being loaded. Instead, my guess is that HA is taking a couple of restarts before actually loading the alexapy dependency using pip.

I'll go ahead and close this, but will monitor if you do test it.

**Comment by hairychris** [comment]
After running

````
rm -rf /appdata/homeassistant/custom_components/alexapy
docker-compose stop homeassistant
docker-compose rm homeassistant
docker-compose up -d homeassistant
````

It is still working so doesn't seem to be that.

This is from a successful start:

````
2019-02-25 02:26:01 INFO (SyncWorker_6) [homeassistant.util.package] Attempting install of alexapy==0.1.0
2019-02-25 02:26:07 INFO (MainThread) [homeassistant.setup] Setting up alexa_media
...
2019-02-25 02:26:09 INFO (MainThread) [homeassistant.setup] Setup of domain alexa_media took 2.4 seconds.
````

This is from an unsuccessful start:

````
2019-02-24 19:48:49 INFO (MainThread) [homeassistant.setup] Setting up alexa_media
2019-02-24 19:48:49 ERROR (MainThread) [homeassistant.setup] Error during setup of component alexa_media
Traceback (most recent call last):
File "/usr/src/app/homeassistant/setup.py", line 154, in _async_setup_component
component.setup, hass, processed_config)  # type: ignore
AttributeError: module 'custom_components.alexa_media' has no attribute 'setup'
````

**Comment by alandtse** [comment]
Thanks for checking.  It sounds like there was some file corruption then before you redid it.

**Comment by chali272** [comment]
> @chali272 That's interesting that it didn't work for you without the alexapy. Are you positive the alexapy folder is necessary? EDIT: Can you confirm there's actually files in alexapy? I just downloaded the zip and since it's a subrepo, it's empty.
> 
> We've had some people looking for an easy way to replace the alexapy version in hass.io, so perhaps this is a workaround.

does not work if i don't have it during the first restart,  i noticed you can delete it after the first start but i think it's like this,  if you dont have it during first install, you dont get the folder in the deep direktion,  if you look in the deep direktion you see that when you have alexapy folder under custom_componets, then that folder get created in deep,  and then there is 3 fils and one folder created in it alexapy folder in the deep section like this (se imige) 
![alexa pi](https://user-images.githubusercontent.com/11187523/53351588-cdbe1000-3921-11e9-9069-f5fe6a102007.JPG)
