### ISSUE TITLE
All Alexa devices unavailable - all notify services missing

### ISSUE THREAD

**Issue by derolli1976** [keatontaylor/custom_components#3029]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Since HA restart this morning, all devices show up as "unavailable" and notify services are missing.

**To Reproduce**

Just did a restart of HA

**Screenshots**

Relevant HA log entries:

2025-10-07 07:21:09.102 INFO (MainThread) [alexapy.alexalogin] Exchanged refresh token for 6 .amazon.de cookies: ['session-id', 'ubid-acbde', 'session-token', 'x-acbde', 'at-acbde', 'sess-at-acbde']
2025-10-07 07:21:10.400 WARNING (MainThread) [alexapy.helpers] alexaapi.get_devices_gql((<alexapy.alexalogin.AlexaLogin object at 0x7f1bfaaea900>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'get'",)
2025-10-07 07:21:10.400 WARNING (MainThread) [alexapy.helpers] alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f1bfaaea900>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'NoneType' object has no attribute 'get'",)
2025-10-07 07:21:10.407 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 'NoneType' object has no attribute 'get'

**System details**

- Home Assistant version: 2025.10.1
- alexa_media version (from `const.py` or HA startup log): 5.7.5
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.8
- Is Amazon [2SV via Authenticator App](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (not 2SV OTP via SMS) enabled?  (y/n):
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

[ha.log](https://github.com/user-attachments/files/22735514/ha.log)

**Additional context**

**Comment by derolli1976** [comment]
Update:
Seems to have been a temporary issue with the amazon API.
Working again.

**Comment by danielbrunt57** [comment]
Did you just upgrade to 2025.10.1?
I had those same errors after upgrading to 2025.10.1 several days ago and it resolved itself after about 10-15 minutes.

**Comment by derolli1976** [comment]
> Did you just upgrade to 2025.10.1? I had those same errors after upgrading to 2025.10.1 several days ago and it resolved itself after about 10-15 minutes.

No, the update was yesterday and the issue arose this morning. But as I sad, it solved itself a couple of hours later so I suspect the API endpoint on the Amazon side.

**Comment by derolli1976** [comment]
Issue seems to be back. See #3032

**Comment by danielbrunt57** [comment]
> Issue seems to be back. See [#3032](https://github.com/alandtse/alexa_media_player/issues/3032)

Could you try removing both Alexa Devices and Alexa Media Player, restart HA and then reinstall just Alexa Media Player and see if it resumes working properly?

**Comment by derolli1976** [comment]
> > Issue seems to be back. See [#3032](https://github.com/alandtse/alexa_media_player/issues/3032)
> 
> Could you try removing both Alexa Devices and Alexa Media Player, restart HA and then reinstall just Alexa Media Player and see if it resumes working properly?

I only have Alexa Media Player installed.
After removing and reconfiguring, no devices are being added.

**Comment by prodigy7** [comment]
> > > Issue seems to be back. See [#3032](https://github.com/alandtse/alexa_media_player/issues/3032)
> > 
> > 
> > Could you try removing both Alexa Devices and Alexa Media Player, restart HA and then reinstall just Alexa Media Player and see if it resumes working properly?
> 
> I only have Alexa Media Player installed. After removing and reconfiguring, no devices are being added.

Same here too. Removed and reinstalled, no new devices are created. Everything up to date, at latest available version
