### PR TITLE
Fix HA 0.88.0 architecture change

### LINKED ISSUE #76: ImportError with home-assistant v. >= 0.88.0
```python
Error loading custom_components.media_player.alexa. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/media_player/alexa.py", line 16, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'MEDIA_TYPE_MUSIC' from 'homeassistant.components.media_player' (/usr/local/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)
```
[Report](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/1871)

Caused by [change in package bundling](https://rc--home-assistant-docs.netlify.com/blog/2019/02/13/release-88/):
```
Note for custom component developers: We are moving to a new file structure. Platforms now live embedded in components. Custom platforms will have to be updated to follow this pattern. This is a breaking change in case your custom platform overrides a built-in platform. Rename your custom platform from, ie light/hue.py to hue/light.py.
```

### PR DESCRIPTION
**Pull request by alandtse**
This resolves #76

### CODE REVIEW

**Comment by dreimer1986** [comment]
Confirmed working on 0.88B1 and B2. But don't forget this one:
WARNING (MainThread) [homeassistant.loader] Integrations need to be in their own folder. Change media_player/alexa.py to alexa/media_player.py. This will stop working soon.

**Comment by alandtse** [comment]
@dreimer1986 Thanks. We'll be making that change for the 1.0.0 branch of this. This was the last fix for the 0.X.X branch.

**Comment by niemyjski** [comment]
I upgraded to 0.88b2 and also changed the folder name and pulled in these changes.. I'm getting

```
Error loading custom_components.media_player.alexa. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/media_player/alexa.py", line 16, in <module>
    from homeassistant.components.media_player import (
ImportError: cannot import name 'MEDIA_TYPE_MUSIC' from 'homeassistant.components.media_player' (/usr/local/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)
```

**Comment by niemyjski** [comment]
I'm not sure the root cause of this. I rebooted a bunch for other changes and it's working again.

**Comment by alandtse** [comment]
@niemyjski The error you reported refers to the breaking change in HA 0.88.0 that this PR was supposed to fix.  This can happen if you didn't pull an updated version from this pull request or the new file wasn't being loaded. Or maybe it could have been a pycache issue. Glad to see it resolved itself.
